# Numpy
= Number Python

Verarbeitung von Zahlen

Kann alles Mathematische
- normale Funktionen
- Berechnungen mit Listen(Arrays) 1D,2D,3D,...

In [2]:
import numpy as np

### Array

In [3]:
a = np.array([1,2,3,4])

In [4]:
a

array([1, 2, 3, 4])

#### Index
Beginnt bei null -> maximal in dem Bsp a[3]

In [5]:
a[0]

np.int64(1)

In [6]:
a[1]

np.int64(2)

In [7]:
a[3]

np.int64(4)

In [8]:
a[-1]

np.int64(4)

In [9]:
a[-2]

np.int64(3)

In [11]:
a[0:2] #ende ist nicht dabei (a[2])

array([1, 2])

In [12]:
a[2:-1]

array([3])

In [13]:
a

array([1, 2, 3, 4])

In [19]:
a[1:4]

array([2, 3, 4])

In [21]:
a[1:] #bis zum Ende

array([2, 3, 4])

In [22]:
a[:2] # von Start bis 2

array([1, 2])

#### Eigenschaften

In [23]:
len(a) # Länge vom Array

4

In [25]:
a.size # Gesamtanzahl der Elemente

4

In [26]:
a.shape

(4,)

In [29]:
a2 = np.array([[1,2],[1,2]])
a2

array([[1, 2],
       [1, 2]])

In [30]:
a2.shape

(2, 2)

In [34]:
len(a2)

2

In [35]:
len(a2[0])

2

In [33]:
a2.size

4

In [37]:
a.ndim # anzahl der Dimensionen

1

In [38]:
a2.ndim

2

In [39]:
a.dtype

dtype('int64')

In [40]:
a2.dtype

dtype('int64')

### Datentypen
Ganzahlen
- int8
- int16
- int32
- int64

Kommazahlen
- float16
- float32
- float64

In [41]:
b = np.array([1,2,3,4,5], dtype = np.int8)

In [42]:
b

array([1, 2, 3, 4, 5], dtype=int8)

#### Matrix
= 2D Array

In [43]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [44]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
c.sum()

np.int64(45)

In [46]:
c.mean()

np.float64(5.0)

In [47]:
c.std()

np.float64(2.581988897471611)

In [48]:
c.var()

np.float64(6.666666666666667)

In [49]:
c.sum(axis = 0) # Summe der Spalten

array([12, 15, 18])

In [50]:
c.sum(axis = 1) # Summe der Zeilen

array([ 6, 15, 24])

In [51]:
np.arange(10) # Array von 0-9 erzeugen

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### Index bei Matritzen

In [53]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
c[0] # erste Zeile

array([1, 2, 3])

In [55]:
c[0:2] # ersten 2 Zeilen

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
c[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
c[1][1] # 2. Zeile, 2. Spalte

np.int64(5)

In [58]:
c[0,0] # Komma geht nur in numpy

np.int64(1)

In [59]:
c[2,0]

np.int64(7)

In [61]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
c[0:3, 0]

array([1, 4, 7])

In [62]:
c[:, 1]

array([2, 5, 8])

In [63]:
c[:, -1]

array([3, 6, 9])

In [64]:
c[1:,1:]

array([[5, 6],
       [8, 9]])

### Vektorisierung
Gesammtes Array mit einer Operation ansprechen

Beliebige Operatoren auf jedes Element des Arrays benutzen

In [65]:
d = np.arange(0,20)

In [66]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [67]:
d+10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [68]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [70]:
d / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

Zwei oder mehrere Arrays können auch miteinander vekortisiert werden

In [71]:
e = np.arange(10,30)

In [72]:
e

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [73]:
d*e

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171, 200, 231, 264,
       299, 336, 375, 416, 459, 504, 551])

Vektorisierung funktioniert auch mit mehrdimensionalen Arrays

In [74]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
c*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [76]:
c*c

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

### Boolean Masken
Ergebnis einer Vektorisierung mit einem boolschen Operator

Im Endeffekt ein Array mit true/false

Wird immer für Filterung verwendet (später bei Pandas, Matplotlib und MashineLearning)

In [77]:
f = np.arange(10)

In [78]:
f

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
g = f>5

In [80]:
g

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [81]:
f[g]

array([6, 7, 8, 9])

In [82]:
f[f>5]

array([6, 7, 8, 9])

### Performance

In [83]:
import time
def measureTime(func):
    start = time.time()
    func()
    end = time.time()
    print(end-start)

In [84]:
anz = 100_000_000

In [85]:
def pythonList():
    x = list(range(anz))
    del(x)

In [92]:
def numpyArray():
    x = np.array(range(anz))
    del(x)

In [93]:
def numpyArange():
    x = np.arange(anz)
    del(x)

In [94]:
measureTime(pythonList)
measureTime(numpyArray)
measureTime(numpyArange)

1.5916318893432617
4.190343379974365
0.14796686172485352


Wie viel speicher braucht die Variable anz?

In [95]:
import sys

In [97]:
sys.getsizeof(anz) #speicherbedarf in byte

28

In [98]:
a

array([1, 2, 3, 4])

In [99]:
a.itemsize # Größe von jedem einzelnen Element
# 8 Byte also 64 Bit

8

In [100]:
b

array([1, 2, 3, 4, 5], dtype=int8)

In [101]:
b.itemsize # 1 Byte Pro element (8 Bit)

1

### Weitere Funktionen

##### random

In [111]:
np.random.random() # Kommazahl zwischen 0 und 1

0.05342784558071756

In [112]:
np.random.random(size=(10)) # 10 Kommazahlen zwischen 0 und 1

array([0.56626692, 0.78997244, 0.67374226, 0.82721963, 0.69246215,
       0.3957871 , 0.32543361, 0.1248029 , 0.65966427, 0.78729086])

In [113]:
np.random.random(size = (5,5))

array([[0.91219524, 0.57074381, 0.98459505, 0.86943066, 0.13687719],
       [0.37559954, 0.52995587, 0.29305417, 0.13033914, 0.97822971],
       [0.20369485, 0.98624977, 0.61794662, 0.7899586 , 0.31485663],
       [0.9095671 , 0.43342956, 0.53524684, 0.46253163, 0.45895115],
       [0.15525215, 0.01329864, 0.37840237, 0.48146291, 0.64326407]])

In [121]:
np.random.randint(10) # Zufallszahl zwichen 0 und 10 (Ganzzahl)

1

In [122]:
np.random.randint(10, size=10)

array([4, 0, 3, 5, 5, 7, 3, 5, 7, 3], dtype=int32)

In [123]:
np.random.randint(10, size=(10,5))

array([[4, 9, 1, 5, 3],
       [8, 6, 5, 8, 3],
       [9, 7, 4, 0, 5],
       [5, 7, 8, 9, 4],
       [3, 2, 3, 9, 3],
       [8, 1, 0, 7, 8],
       [8, 3, 3, 3, 5],
       [5, 7, 8, 7, 8],
       [7, 5, 2, 6, 2],
       [2, 1, 3, 7, 6]], dtype=int32)

In [124]:
np.random.randint(10, size=(10,5), dtype = np.int8)

array([[7, 3, 7, 4, 3],
       [8, 9, 5, 4, 9],
       [5, 5, 4, 6, 4],
       [4, 9, 3, 5, 5],
       [4, 1, 4, 0, 2],
       [5, 1, 1, 3, 8],
       [1, 8, 8, 2, 5],
       [0, 1, 6, 5, 0],
       [6, 4, 8, 5, 2],
       [3, 2, 0, 3, 0]], dtype=int8)

##### reshape
Form eines Arrays verändern (1D -> 2D, 2D -> 1D)

In [125]:
h = np.random.randint(10, size=(10,5), dtype = np.int8)

In [126]:
h

array([[1, 4, 6, 5, 9],
       [6, 1, 3, 2, 8],
       [8, 2, 2, 0, 2],
       [9, 3, 3, 6, 2],
       [3, 1, 9, 7, 7],
       [7, 9, 3, 6, 1],
       [2, 9, 0, 0, 4],
       [2, 2, 3, 8, 1],
       [6, 0, 3, 9, 0],
       [7, 9, 5, 1, 1]], dtype=int8)

In [127]:
h.reshape(5,10)

array([[1, 4, 6, 5, 9, 6, 1, 3, 2, 8],
       [8, 2, 2, 0, 2, 9, 3, 3, 6, 2],
       [3, 1, 9, 7, 7, 7, 9, 3, 6, 1],
       [2, 9, 0, 0, 4, 2, 2, 3, 8, 1],
       [6, 0, 3, 9, 0, 7, 9, 5, 1, 1]], dtype=int8)

In [128]:
h.reshape(50)

array([1, 4, 6, 5, 9, 6, 1, 3, 2, 8, 8, 2, 2, 0, 2, 9, 3, 3, 6, 2, 3, 1,
       9, 7, 7, 7, 9, 3, 6, 1, 2, 9, 0, 0, 4, 2, 2, 3, 8, 1, 6, 0, 3, 9,
       0, 7, 9, 5, 1, 1], dtype=int8)

In [129]:
h.reshape(h.size)

array([1, 4, 6, 5, 9, 6, 1, 3, 2, 8, 8, 2, 2, 0, 2, 9, 3, 3, 6, 2, 3, 1,
       9, 7, 7, 7, 9, 3, 6, 1, 2, 9, 0, 0, 4, 2, 2, 3, 8, 1, 6, 0, 3, 9,
       0, 7, 9, 5, 1, 1], dtype=int8)

In [130]:
h.reshape(-1) # alle Dimensionen entfernen

array([1, 4, 6, 5, 9, 6, 1, 3, 2, 8, 8, 2, 2, 0, 2, 9, 3, 3, 6, 2, 3, 1,
       9, 7, 7, 7, 9, 3, 6, 1, 2, 9, 0, 0, 4, 2, 2, 3, 8, 1, 6, 0, 3, 9,
       0, 7, 9, 5, 1, 1], dtype=int8)

In [131]:
i = np.arange(25)

In [132]:
i

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [133]:
i.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

##### linspace
Erzeugt ein Array von X bis Y mit Z Elementen
Alle Abstände sind gleich groß

In [137]:
np.linspace(0, 20, 101)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8,
       11. , 11.2, 11.4, 11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8, 13. ,
       13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. , 15.2,
       15.4, 15.6, 15.8, 16. , 16.2, 16.4, 16.6, 16.8, 17. , 17.2, 17.4,
       17.6, 17.8, 18. , 18.2, 18.4, 18.6, 18.8, 19. , 19.2, 19.4, 19.6,
       19.8, 20. ])

In [138]:
np.arange(0,101)/5

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8,
       11. , 11.2, 11.4, 11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8, 13. ,
       13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. , 15.2,
       15.4, 15.6, 15.8, 16. , 16.2, 16.4, 16.6, 16.8, 17. , 17.2, 17.4,
       17.6, 17.8, 18. , 18.2, 18.4, 18.6, 18.8, 19. , 19.2, 19.4, 19.6,
       19.8, 20. ])

##### zeros, ones
Erzeugt ein Array mit nur 0en oder 1en

In [139]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [140]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [141]:
np.ones(10)==1

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [142]:
np.ones(10)==0

array([False, False, False, False, False, False, False, False, False,
       False])

##### hstack, vstack
Arrays zusammenbauen (horizontal, vertikal)

In [145]:
r= h[5:]

In [146]:
r

array([[7, 9, 3, 6, 1],
       [2, 9, 0, 0, 4],
       [2, 2, 3, 8, 1],
       [6, 0, 3, 9, 0],
       [7, 9, 5, 1, 1]], dtype=int8)

In [147]:
l = h[:5]

In [148]:
l

array([[1, 4, 6, 5, 9],
       [6, 1, 3, 2, 8],
       [8, 2, 2, 0, 2],
       [9, 3, 3, 6, 2],
       [3, 1, 9, 7, 7]], dtype=int8)

In [149]:
np.hstack([l,r]) # l und r horizontal aneinander hängen
# WICHTIG: Die einzelnen Arrays müssen inerhalb der Funktion zusammengruppiert werden

array([[1, 4, 6, 5, 9, 7, 9, 3, 6, 1],
       [6, 1, 3, 2, 8, 2, 9, 0, 0, 4],
       [8, 2, 2, 0, 2, 2, 2, 3, 8, 1],
       [9, 3, 3, 6, 2, 6, 0, 3, 9, 0],
       [3, 1, 9, 7, 7, 7, 9, 5, 1, 1]], dtype=int8)

In [150]:
np.vstack([l,r]) # l und r horizontal aneinander hängen
# WICHTIG: Die einzelnen Arrays müssen inerhalb der Funktion zusammengruppiert werden

array([[1, 4, 6, 5, 9],
       [6, 1, 3, 2, 8],
       [8, 2, 2, 0, 2],
       [9, 3, 3, 6, 2],
       [3, 1, 9, 7, 7],
       [7, 9, 3, 6, 1],
       [2, 9, 0, 0, 4],
       [2, 2, 3, 8, 1],
       [6, 0, 3, 9, 0],
       [7, 9, 5, 1, 1]], dtype=int8)

Aufgabe: Summen jeder Spalte unten anhängen

In [152]:
l

array([[1, 4, 6, 5, 9],
       [6, 1, 3, 2, 8],
       [8, 2, 2, 0, 2],
       [9, 3, 3, 6, 2],
       [3, 1, 9, 7, 7]], dtype=int8)

In [151]:
l.sum(axis=0)

array([27, 11, 23, 20, 28])

In [154]:
np.vstack([l, l.sum(axis=0)])

array([[ 1,  4,  6,  5,  9],
       [ 6,  1,  3,  2,  8],
       [ 8,  2,  2,  0,  2],
       [ 9,  3,  3,  6,  2],
       [ 3,  1,  9,  7,  7],
       [27, 11, 23, 20, 28]])

In [156]:
y=np.arange(25)

In [157]:
y.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])