In [1]:
import numpy as np

## 1. Erstellung von Arrays
Erstelle ein Array mit Zahlen von -10 bis (einschließlich) 10

In [2]:
np.arange(-10, 11)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10])

Erstelle ein 5x5 Array mit den Zahlen von 0 bis 24

In [4]:
np.arange(25).reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

Erstelle ein Array mit ungeraden Zahlen von 0 bis 100

In [5]:
np.arange(1, 101, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

Erstelle ein Array befüllt mit Kommazahlen von 0 bis 10 (Schrittgröße 0.1)

In [6]:
np.arange(0, 10, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

Erstelle ein Array von 50 bis 100 und summiere alle Zahlen

In [7]:
np.arange(50, 101).sum()

np.int64(3825)

Erstelle ein 5x10 Array und berechne den Mittelwert jeder Zeile

In [8]:
np.random.randint(10, size=(5, 10)).mean(axis=1)

array([5.2, 4.8, 6.2, 3.5, 4.7])

Erstelle ein 5x10 Array und berechne die Summe jeder Spalte

In [26]:
np.random.randint(10, size=(5, 10)).sum(axis=0)

array([24, 21, 17, 19, 25, 21, 22, 22, 15, 23])

## 2. Vektorisierung

Erzeuge ein Array mit zufälligen Kommazahlen von 0 bis 1 und finde alle Elemente die mindestens 0.5 sind

In [9]:
x = np.random.random(10)
x[x > 0.5]

array([0.67515213, 0.96436183, 0.71170186, 0.71347304, 0.94706926])

Erzeuge ein Array der Form x^2 von 1 bis 20
 - Finde nun in diesem Array alle Zahlen die gerade sind

In [10]:
np.arange(1, 21) ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400])

In [11]:
y = np.arange(1, 21) ** 2
y[y % 2 == 0]

array([  4,  16,  36,  64, 100, 144, 196, 256, 324, 400])

Erzeuge ein Array mit 10 Stellen befüllt mit ganzen Zufallszahlen von 0 bis 100. Finde alle Elemente die maximal 80% des Höchstwertes sind.

In [16]:
z = np.random.randint(100, size=10)
m = z.max()
m

np.int32(99)

In [17]:
z[z > (m * 0.8)]

array([99, 85, 92], dtype=int32)

Erzeuge ein 10x10 Array befüllt mit ganzen Zufallszahlen von 0 bis 10. Gib nun alle Zeilen aus, bei denen der neue Mittelwert der entsprechenden Zeile größer als 5 ist.

In [19]:
a = np.random.randint(10, size=(10, 10))

In [20]:
a.mean(axis=1)

array([3.3, 5.1, 4.3, 4.8, 5. , 6.5, 5.1, 4.8, 4.5, 3.6])

In [21]:
a[a.mean(axis=1) > 5]

array([[6, 6, 7, 7, 4, 7, 1, 0, 6, 7],
       [9, 8, 2, 7, 6, 8, 5, 7, 4, 9],
       [3, 4, 1, 6, 4, 9, 4, 6, 9, 5]], dtype=int32)

Erzeuge zwei Arrays mit gleicher Länge und Zufallszahlen. Finde alle Werte, die in beiden Arrays an derselben Stelle sind
- Finde zusätzlich die Stellen der gleichen Zahlen

In [22]:
b = np.random.randint(10, size=100)
c = np.random.randint(10, size=100)

In [23]:
b == c

array([False,  True, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False])

In [24]:
# Gleiche Werte
b[b == c]

array([3, 3, 8, 5, 7, 2, 0, 3], dtype=int32)

In [25]:
# Stellen
np.arange(100)[b == c]

array([ 1, 11, 29, 38, 53, 67, 75, 95])

In [26]:
# Beides gleichzeitig
maske = b == c
np.vstack((np.arange(100)[maske], b[maske], c[maske]))

array([[ 1, 11, 29, 38, 53, 67, 75, 95],
       [ 3,  3,  8,  5,  7,  2,  0,  3],
       [ 3,  3,  8,  5,  7,  2,  0,  3]])